version: '3'

services:
  web:
    environment:
      - APACHE_RUN_USER=#1000
    build:
      # context: ./dockers/web
      context: ./
      dockerfile: ./dockers/web/Dockerfile
    ports:
      - 8000:80
      - 8001:81
    volumes:
      - ./:/var/www/html
