const animals = [
    "Aardvark",
    "Addax",
    "Adelie Penguin",
    "African Elephant",
    "African Forest Elephant",
    "African Lion",
    "African Penguin",
    "African Spurred Tortoise",
    "African Wild Dog",
    "Africanized Bee",
    "Allen’s Swamp Monkey",
    "Alligator",
    "Allis Shad",
    "Alpine Ibex",
    "Amazonian Manatee",
    "American Oystercatcher Bird",
    "Anaconda Snake",
    "Ant",
    "Aquatic Warbler",
    "Arctic Wolf",
    "Armadillo",
    "Asian Elephant",
    "Asian Lion",
    "Atlantic Puffin",
    "Atlantic Spotted Dolphin",
    "Atlas Beetle",
    "Audubon’s Shearwater",
    "Australasian Grebe",
    "Australian Dingo",
    "Australian Pelican",
    "Australian Swiftlet",
    "Bactrian Camel",
    "Badger",
    "Bean Goose",
    "Bee",
    "Beetle",
    "Bengal Tiger",
    "Big Eyed Squirrel Fish",
    "Bison",
    "Black Caiman",
    "Black House Spider",
    "Black Mamba Snake",
    "Black Necked Stilt",
    "Black Rhinoceros",
    "Black Widow Spider",
    "Blacktip Reef Shark",
    "Blacktip Shark",
    "Blister Beetle",
    "Blue and Yellow Macaw",
    "Blue Whale",
    "Blue-footed Booby Bird",
    "Boa Constrictor Snake",
    "Bottlenose Dolphin",
    "Bowhead Whale",
    "Brandling Worm",
    "Brazilian Wandering Spider",
    "British Mice",
    "British Mole",
    "British Water Vole",
    "British Wild Cat",
    "Broad-Snouted Caiman",
    "Brown Recluse Spider",
    "Brown Trout",
    "Bumble Bee",
    "Burying Beetle",
    "Butterfly",
    "Camel",
    "Campbell’s Dwarf Hamster",
    "Cape Gannet Bird",
    "Capercaillie",
    "Capuchin Monkey",
    "Capybara",
    "Caracal",
    "Cardinal Bird",
    "Caribbean Reef Shark",
    "Caribou",
    "Cat",
    "Centipede",
    "Cheetah",
    "Chickaree",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Chinese Hamster",
    "Chinstrap Penguin",
    "Chipmunk",
    "Christmas Beetle",
    "Cicada Killer Wasp",
    "Click Beetle",
    "Commerson Dolphin",
    "Common Buzzard",
    "Common Dolphin",
    "Common Frog",
    "Common Hippopotamu",
    "Common Kingfisher",
    "Common Lizard",
    "Common Newt",
    "Common Palm Civet",
    "Common Seal",
    "Common Toad",
    "Common Wasp",
    "Copperhead Snake",
    "Corncrake",
    "Cottonmouth Snake",
    "Cow",
    "Coyote",
    "Crab Plover",
    "Crab",
    "Crocodile",
    "Cuban Solenodon",
    "Cuviers Dwarf Caiman",
    "Darkling Beetle",
    "De Brazza’s Monkey",
    "Deer",
    "Dog",
    "Dolphin",
    "Domestic Pig",
    "Dragonfly",
    "Dromedary Camel",
    "Duck-billed Platypu",
    "Duck",
    "Dung Beetle",
    "Earthworm",
    "Eastern Lowland Gorilla",
    "Eastern Wolf",
    "Elephant Seal",
    "Elephant",
    "Elk",
    "Emperor Penguin",
    "Emu",
    "Erect-Crested Penguin",
    "Ethiopian Wolf",
    "Eurasian Water Shrew",
    "Eurasian Wolf",
    "Eurasian Wryneck",
    "European Hare",
    "European Otter",
    "False Black Widow Spider",
    "Fennec Fox",
    "Field Vole",
    "Fiji Blue Devil Damsel Fish",
    "Fiordland Crested Penguin",
    "Flatworm",
    "Fungus Beetle",
    "Funnel Web Spider",
    "Galapagos Barn Owl",
    "Galapagos Black Tipped Shark",
    "Galapagos Brown Noddy Tern",
    "Galapagos Brown Pelican Bird",
    "Galapagos Brydes Whale",
    "Galapagos Dark Billed Cuckoo",
    "Galapagos Dove",
    "Galapagos Eel",
    "Galapagos Fin Whale",
    "Galapagos Finch",
    "Galapagos Flamingo",
    "Galapagos Flightless Cormorant Sea Bird",
    "Galapagos Flycatcher Bird",
    "Galapagos Fur Seal",
    "Galapagos Gecko",
    "Galapagos Giant Tortoise",
    "Galapagos Great Blue Heron Bird",
    "Galapagos Great Frigate Bird",
    "Galapagos Green Sea Turtle",
    "Galapagos Hammerhead Shark",
    "Galapagos Hawk",
    "Galapagos Hoary Bat",
    "Galapagos Humpback Whale",
    "Galapagos Killer Whale",
    "Galapagos Land Iguana",
    "Galapagos Lava Gull Bird",
    "Galapagos Lava Heron Bird",
    "Galapagos Lava Lizard",
    "Galapagos Marine Iguana",
    "Galapagos Masked Booby Bird",
    "Galapagos Minke Whale",
    "Galapagos Mockingbird",
    "Galapagos Nazca Booby Bird",
    "Galapagos Penguin",
    "Galapagos Rail Bird",
    "Galapagos Ray",
    "Galapagos Red Bat",
    "Galapagos Red Billed Tropic Bird",
    "Galapagos Red Footed Booby Bird",
    "Galapagos Rice Rat",
    "Galapagos Sea Lion",
    "Galapagos Short Eared Owl",
    "Galapagos Short Finned Pilot Whale",
    "Galapagos Silky Shark",
    "Galapagos Smooth Billed Ani Bird",
    "Galapagos Snake",
    "Galapagos Sperm Whale",
    "Galapagos Storm Petrel Bird",
    "Galapagos Swallow Tailed Gull",
    "Galapagos Waved Albatros",
    "Galapagos Whale Shark",
    "Galapagos Whimbrel Bird",
    "Galapagos White Cheeked Pintail Duck",
    "Galapagos White Tipped Reef Shark",
    "Galapagos Willet Bird",
    "Galapagos Yellow Warbler Bird",
    "Galapagos Yellow-Crowned Night Heron",
    "Gemsbok",
    "Gentoo Penguin",
    "Gerenuk",
    "Gharial",
    "Giant Anteater",
    "Giant Panda Bear",
    "Giant Sable Antelope",
    "Giraffe",
    "Goat",
    "Gold, Silver and Blue Monkey",
    "Golden Eagle",
    "Golden Pheasant",
    "Gorilla",
    "Grasshopper",
    "Great Bittern",
    "Great Crested Newt",
    "Great Green Macaw",
    "Great White African Pelican",
    "Great White Shark",
    "Greater Flamingo",
    "Greater Horseshoe Bat",
    "Greater Mouse-Eared Bat",
    "Greater Spot-Nosed Monke",
    "Green Crab",
    "Green Scarab Beetle",
    "Grevy’s Zebra",
    "Grey Jungle Fowl Bird",
    "Grey Loerie bird",
    "Grey Partridge",
    "Grey Seal",
    "Grey Wolf",
    "Grivet Monkey",
    "Grizzly Bear",
    "Ground Beetle",
    "Ground Centipede",
    "Guinea Pig",
    "Hamerkop Bird",
    "Hamster",
    "Harbour Porpoise",
    "Harp Seal",
    "Hazel Dormouse",
    "Hectors Dolphin",
    "Hedgehog",
    "Hermit Crab",
    "Hippopotamus",
    "Hobo Spider",
    "Honey Bee",
    "Hoopoe Bird",
    "Hornet",
    "Horse",
    "Horseshoe Crab",
    "House Centipede",
    "Howler Monkey",
    "Humboldt Penguin",
    "Huntsman Spider",
    "Hydrozoan Jellyfish",
    "Ibisbill Bird",
    "Impala",
    "Indian Cuckoo Bird",
    "Indian Rhinoceros",
    "Indian Skimmer Bird",
    "Italian Wolf",
    "Jackal",
    "Jaguar",
    "Jambu Fruit Dove",
    "Japanese Spider Crab",
    "Javan Rhinoceros",
    "Jellyfish",
    "Katipo Spider",
    "Kea Parrot",
    "Kestrel Bird",
    "King Cobra Snake",
    "King Penguin",
    "Kinkajou",
    "Kitten",
    "Koala",
    "Komodo Dragon",
    "Ladybird",
    "Laughing Kookaburra",
    "Lemming",
    "Lemur",
    "Lion",
    "Little Fairy Penguin",
    "Lizard",
    "Llama",
    "Long Horned Beetle",
    "Longhorn Cowfish",
    "Lynx",
    "Macaque Monkey",
    "Macaroni Penguin",
    "Magellanic Penguin",
    "Manatee",
    "Maned Wolf",
    "Manx Shearwater Bird",
    "Marine Angelfish",
    "Markhor",
    "Masai Giraffe",
    "Masked Finfoot Bird",
    "Mealy Parrot",
    "Meerkat",
    "Mexican Wolf",
    "Mice",
    "Military Macaw Parrot",
    "Milkweed Beetle",
    "Millipede",
    "Monkey",
    "Moose",
    "Morpho Butterfly",
    "Moth",
    "Mountain Goat",
    "Mountain Gorilla",
    "Mountain Zebra",
    "Mouse Spider",
    "Mud Dauber Wasp",
    "Musk Ox",
    "Natterjack Toad",
    "New World Monkey",
    "New World Tarantula Spider",
    "Northern Short-tailed Shrew",
    "Nurse Shark",
    "Ocelot",
    "Okapi",
    "Old World Monkey",
    "Old World Tarantula Spider",
    "Opossum",
    "Orangutan",
    "Orb Weaver Spider",
    "Oryx (Antelope)",
    "Osprey",
    "Ostrich Bird",
    "Pantropical Spotted Dolphin",
    "Paper Wasp",
    "Parasitic Bee",
    "Peafowl Peacock",
    "Peccary (Javelina)",
    "Penguin",
    "Peruvian Fox",
    "Pig",
    "Pine Marten",
    "Piranha Fish",
    "Plains Zebra",
    "Poison Arrow Frog",
    "Polar Bear",
    "Polecat",
    "Pollan Fish",
    "Porcupine",
    "Potter Wasp",
    "Praying Mantis",
    "Preuss’s Monkey",
    "Puma",
    "Pygmy Hippopotamus",
    "Quagga Zebra",
    "Quoll",
    "Rabbit",
    "Racoon",
    "Rainbow Bee Eater",
    "Ratel",
    "Rattlesnake",
    "Red Back Jumping Spider",
    "Red British Squirrel",
    "Red Fox",
    "Red Kangaroo",
    "Red Kite",
    "Red Panda",
    "Red Rock Crab",
    "Red Wolf",
    "Red-backed Shrike",
    "Reticulated Giraffe",
    "Rhinoceros",
    "Rhinoceros Beetle",
    "Right Whale",
    "Risso’s Dolphin",
    "Roborovski Hamster",
    "Rockhopper Penguin",
    "Rough-Toothed Dolphin",
    "Royal Penguin",
    "Sacred Ibis Bird",
    "Saki Monkey",
    "Sally Lightfoot Crab",
    "Sand Lizard",
    "Scarlet Macaw",
    "Schneiders Dwarf Caiman",
    "Scottish Crossbill",
    "Sea Lion",
    "Sea Snake",
    "Seahorse",
    "Seal",
    "Secretary Bird",
    "Serval",
    "Shark",
    "Sheep",
    "Silvery Gibbon",
    "Six Eyed Sand Spider",
    "Skipper Butterfly",
    "Skylark",
    "Slender Loris",
    "Sloth",
    "Snake",
    "Snares Penguin",
    "Snow Leopard",
    "Snowshoe Hare",
    "Solitary Bee",
    "Song Thrush",
    "Southern Short-tailed Shrew",
    "Spectacled Bear",
    "Spectacled/Common Caiman",
    "Spider Monkey",
    "Spider",
    "Spinner Dolphin",
    "Spotted Beetle",
    "Squirrel Monkey",
    "St. Andrew’s Cross Spider",
    "Stag Beetle",
    "Stingless Bee",
    "Stink Bug",
    "Stoat",
    "Stone Curlew",
    "Stone Dwelling Centipede",
    "Striped Dolphin",
    "Striped Hyena",
    "Sugar Maple Borer Beetle",
    "Sumatran Rhinoceros",
    "Syrian Hamster",
    "Tamarin Monkey",
    "Tangle Web Spider",
    "Tapir",
    "Tarantula Spider",
    "Tawny Eagle",
    "Tawny Frogmouth",
    "Teira Batfish",
    "Thomson’s Gazelle",
    "Tiger Shark",
    "Titi Monkey",
    "Toco Toucan",
    "Tortoise",
    "Trapdoor Spider",
    "Tuatara",
    "Tundra Wolf",
    "Turtle",
    "Vampire Bat",
    "Vendace Fish",
    "Vulture",
    "Wallaby",
    "Wasp",
    "Water Beetle",
    "Weasel",
    "Weevil Beetle",
    "West African Manatee",
    "West Indian Manatee",
    "Western Lowland Gorilla",
    "Whale",
    "White Bengal Tiger",
    "White Rhino",
    "White Stork",
    "White-clawed Crayfish",
    "Wild Boar",
    "Wild Rabbit",
    "Wildebeest",
    "Winter White Russian Hamster",
    "Wolf Spider",
    "Wolverine",
    "Wolf",
    "Wombat",
    "Worm",
    "Yacare Caimans",
    "Yellow jacket Wasp",
    "Yellow Sac Spider",
    "Yellow-eyed Penguin",
    "Zebra",
];
export default animals;
